### ISSUE TITLE
cfg.hardware.nworkers

### ISSUE THREAD

**Issue by MertArslanoglu** [kyotovision-public/deepoint#2]
Hello,
I am running the demo.py code with your example.mp4 video with the command you gave:
python src/demo.py movie=./demo/example.mp4 lr=l ckpt=./models/weight.ckpt

However, it takes too long to process the video, it takes more than 1 hour to receive the output. As I checked the main bottleneck is the MovieDataset class which takes too long to run. 

I have done all above with cfg.hardware.nworkers =0.

When I increase the cfg.hardware.nworkers to 2, it gets frozen inside the __get_item__ method and I can not understand the reason.

Do you have any idea about getting the code faster to process videos in real time or something closer to real time?

Thank you in advance.

**Comment by swnakamura** [comment]
Thank you for your interest in our paper.
This demo is not intended to run in real-time, but there are several possible improvements. One of them would be to share the initial feature estimation across inferences, as most of the input frames overlap for video processing.I presume, though, it would be difficult to run the inference in real-time as is. Making the Transformer model smaller could help.
