### ISSUE TITLE
Google Drive Downloading Dataset

### ISSUE THREAD

**Issue by YilmazKadir** [kyotovision-public/deepoint#3]
Thank you so much for making the code and dataset available. I am trying to download the data but it says download quota exceeded in Google Drive. Is there an alternative way to download it? Have you considered hosting the dataset yourself?

**Comment by swnakamura** [comment]
Thank you for your interest in our dataset! Unfortunately, no, we don't have our hosting system. Please wait until the restriction of Google Drive is lifted.
