### ISSUE TITLE
Dataset Distance Units

### ISSUE THREAD

**Issue by MertArslanoglu** [kyotovision-public/deepoint#4]
First of all, thank you for your excellent work on this project. I have a question regarding the units of measurement used in the dataset.

Could you please clarify what distance units are used to create the dataset? Are the measurements in meters? Specifically, are the human poses properly labeled in meters?

I checked the provided keypoints in the triangulation.pickle file, and I noticed that the height of the person in 2023-01-17-livingroom/take1 at frame 300 is approximately 50 units. This seems unusually low if the units are in meters.

Could you please provide information about the distance units used in the dataset?

Thank you in advance for your assistance.

**Comment by swnakamura** [comment]
Thank you for your interest in our work, and sorry for late reply!

Sorry, but we didn't measure the distance in units, as we only needed the direction of pointing to train the network and didn't care about the scaling.
For your information, the length of the side of the printed ArUco markers is about 17.65 cm each. I hope this information helps you. (For example, you might be able to rescale the environment such that the markers have this size on average, but it can be inaccurate as the triangulation is not perfect and markers are very small compared to the environment itself.)
